import os

env = DefaultEnvironment(ENV=os.environ, tools=['mingw', 'qt5'])

sources = env.SConscript('src/SConscript', exports='env', variant_dir='build')

program = env.Program('bin/main', sources)

env.Default(program)
